name: macOS
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setting the Environment Up.
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        USER_PWD: ${{ secrets.USER_PWD }}
        AMI_PEM: ${{ secrets.AMI_PEM }}
        BACKUP_SRC: ${{ secrets.BACKUP_SRC }}
        AWS_EC2: ${{ secrets.AWS_EC2 }}
      run: source setup.sh "$USER_PWD" "$USER_PWD" "$NGROK_AUTH_TOKEN" "$BACKUP_SRC" "$AWS_EC2"
    - name: ngrok is now listening to SSH connections on...
      run: curl --silent http://127.0.0.1:4040/api/tunnels | jq '.tunnels[0].public_url'
    - name: Setup tmate Session
      uses: mxschmitt/action-tmate@v2
